import Attack from './activatedSkills/attack';
import Barrage from './activatedSkills/barrage';
import Bolt from './activatedSkills/bolt';
import Empower from './activatedSkills/empower';
import Enlarge from './activatedSkills/enlarge';
import Enrage from './activatedSkills/enrage';
import Freeze from './activatedSkills/freeze';
import FreezeSelf from './activatedSkills/freezeSelf';
import Frostbreath from './activatedSkills/frostbreath';
import Heal from './activatedSkills/heal';
import Hex from './activatedSkills/hex';
import Legion from './activatedSkills/legion';
import PoisonBolt from './activatedSkills/poisonBolt';
import Protect from './activatedSkills/protect';
import Scorch from './activatedSkills/scorch';
import ScorchSelf from './activatedSkills/scorchSelf';
import Scorchbreath from './activatedSkills/scorchbreath';
import Weaken from './activatedSkills/weaken';
import WeakenSelf from './activatedSkills/weakenSelf';
import WingWard from './activatedSkills/wingWard';
import Berserk from './triggeredSkills/onAttack/berserk';
import Daze from './triggeredSkills/onAttack/daze';
import Nullify from './triggeredSkills/onAttack/nullify';
import Poison from './triggeredSkills/onAttack/poison';
import Reinforce from './triggeredSkills/onAttack/reinforce';
import Siphon from './triggeredSkills/onAttack/siphon';
import Venom from './triggeredSkills/onAttack/venom';
import Corrosive from './triggeredSkills/onDamaged/corrosive';
import Emberhide from './triggeredSkills/onDamaged/emberhide';
import Fury from './triggeredSkills/onDamaged/fury';
import Vengeance from './triggeredSkills/onDamaged/vengeance';
import Regenerate from './triggeredSkills/turnEnd/regenerate';
import Invisibility from './triggeredSkills/turnStart/invisibility';
import Valor from './triggeredSkills/turnStart/valor';
import ValorTriggered from './triggeredSkills/turnStart/valorTriggered';
import Ward from './triggeredSkills/turnStart/ward';

// maintain legacy skill names
export const absorb = getInstance(Ward);
export const attack = getInstance(Attack);
export const barrage = getInstance(Barrage);
export const berserk = getInstance(Berserk);
export const burn = getInstance(Scorch);
export const burnself = getInstance(ScorchSelf);
export const corrosive = getInstance(Corrosive);
export const counter = getInstance(Vengeance);
export const counterburn = getInstance(Emberhide);
export const daze = getInstance(Daze);
export const enfeeble = getInstance(Hex);
export const enlarge = getInstance(Enlarge);
export const enrage = getInstance(Enrage);
export const evade = getInstance(Invisibility);
export const evadebarrier = getInstance(WingWard);
export const frost = getInstance(Frostbreath);
export const fury = getInstance(Fury);
export const heal = getInstance(Heal);
export const jam = getInstance(Freeze);
export const jamself = getInstance(FreezeSelf);
export const leech = getInstance(Siphon);
export const legion = getInstance(Legion);
export const nullify = getInstance(Nullify);
export const poison = getInstance(Poison);
export const poisonstrike = getInstance(PoisonBolt);
export const protect = getInstance(Protect);
export const rally = getInstance(Empower);
export const regenerate = getInstance(Regenerate);
export const reinforce = getInstance(Reinforce);
export const scorchbreath = getInstance(Scorchbreath);
export const strike = getInstance(Bolt);
export const valor = getInstance(Valor);
export const valorTriggered = getInstance(ValorTriggered);
export const venom = getInstance(Venom);
export const weaken = getInstance(Weaken);
export const weakenself = getInstance(WeakenSelf);

function getInstance(Constructor) {
    return new Constructor();
}
